name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: dotnet restore PidrobitOK.AuthService/PidrobitOK.AuthService.csproj
    - run: dotnet build PidrobitOK.AuthService/PidrobitOK.AuthService.csproj --no-restore --configuration Release
    - run: dotnet test PidotbitOK.Auth/PidrobitOK.Auth_Test/PidrobitOK.AuthService_Test.csproj --no-build --verbosity normal

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: dotnet restore PidrobitOK.AuthService/PidrobitOK.AuthService.csproj
    - run: dotnet build PidrobitOK.AuthService/PidrobitOK.AuthService.csproj --no-restore --configuration Release
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: ./PidrobitOK.AuthService/Dockerfile
        push: true
        tags: nureternovyidaniil/pidrobitok-auth-service:latest
